spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl?useUnicode=true&characterEncoding=ZHS16GBK
    username: zzy
    password: 123456
    driver-class-name: oracle.jdbc.OracleDriver
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 128MB  # 设置最大文件大小
      max-request-size: 128MB  # 设置请求总大小

server:
  port: 8082


mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.example.demo.Model
